### ISSUE TITLE
Unable to locate a class or view for component [spinner]. please give me the solution for this issues.

### ISSUE THREAD

**Issue by SingaravelC** [gehrisandro/laravel-http-psr18#1]
![Screenshot (55)](https://github.com/gehrisandro/laravel-http-psr18/assets/161044694/4eccf856-6f0d-49b1-86c3-57c522018fe2)

**Comment by gehrisandro** [comment]
not releated to this package

**Comment by SingaravelC** [comment]
I guide to in this website sir. https://gehri.dev/blog/how-to-use-the-openai-assistants-api-in-php-and-laravel . please solve this is issues. i am kindly request sir
